#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/yogi

PRODUCT_COPY_FILES += \
    vendor/google/yogi/proprietary/odm/etc/build.prop:$(TARGET_COPY_OUT_ODM)/etc/build.prop \
    vendor/google/yogi/proprietary/odm/etc/group:$(TARGET_COPY_OUT_ODM)/etc/group \
    vendor/google/yogi/proprietary/odm/etc/passwd:$(TARGET_COPY_OUT_ODM)/etc/passwd \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_file_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_file_contexts \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_hwservice_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_hwservice_contexts \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_mac_permissions.xml:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_mac_permissions.xml \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_property_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_property_contexts \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_seapp_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_seapp_contexts \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_sepolicy.cil:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_sepolicy.cil \
    vendor/google/yogi/proprietary/odm/etc/selinux/odm_service_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_service_contexts

PRODUCT_PACKAGES += \
    com.google.edgetpu_app_service-V10-ndk \
    com.google.edgetpu_vendor_service-V2-ndk \
    libMIPC-native \
    libimsstack \
    libmipc \
    libmosey_daemon_ffi \
    libmtkproperty \
    libmtkrillog \
    libpixeldisplaymanager_jni \
    libpixelimsmedia \
    libpowerstatshaldataprovider \
    libtrm \
    vendor.google.whitechapel.audio.audioext@4.0 \
    vendor.google.whitechapel.audio.extension-V8-ndk \
    backup_ota_log \
    bluetooth_gci \
    gs_watchdogd \
    android.hidl.allocator@1.0-service \
    vendor.google.edgetpu_app_service@1.0-service \
    vendor.google.whitechapel.audio.hal.parserservice \
    mosey_server \
    sconed \
    userdata_alias_remove

PRODUCT_COPY_FILES += \
    vendor/google/yogi/proprietary/vendor/etc/Khronos/OpenCL/vendors/IMG.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/vendors/IMG.icd \
    vendor/google/yogi/proprietary/vendor/etc/aidl/le_audio/aidl_audio_set_configurations.json:$(TARGET_COPY_OUT_VENDOR)/etc/aidl/le_audio/aidl_audio_set_configurations.json \
    vendor/google/yogi/proprietary/vendor/etc/aidl/le_audio/aidl_audio_set_scenarios.json:$(TARGET_COPY_OUT_VENDOR)/etc/aidl/le_audio/aidl_audio_set_scenarios.json \
    vendor/google/yogi/proprietary/vendor/etc/angle/feature_config_vk.binarypb:$(TARGET_COPY_OUT_VENDOR)/etc/angle/feature_config_vk.binarypb \
    vendor/google/yogi/proprietary/vendor/etc/aoc/phonebooth/PLM_PB_Rel_Ver_IR7_ESS_FP16-graph-custom_op.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/phonebooth/PLM_PB_Rel_Ver_IR7_ESS_FP16-graph-custom_op.tflite \
    vendor/google/yogi/proprietary/vendor/etc/app_qos_mappings.json:$(TARGET_COPY_OUT_VENDOR)/etc/app_qos_mappings.json \
    vendor/google/yogi/proprietary/vendor/etc/app_qos_processes.json:$(TARGET_COPY_OUT_VENDOR)/etc/app_qos_processes.json \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth/bluetooth_channel_sounding_calibration.json:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bluetooth_channel_sounding_calibration.json \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth/bt_vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor.conf \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth/bt_vendor_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor_overlay.conf \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth/firmware_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/firmware_config.json \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth/hal_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/hal_config.json \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth_power_limits.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits.csv \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth_power_limits_CA.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_CA.csv \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth_power_limits_EU.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_EU.csv \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth_power_limits_JP.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_JP.csv \
    vendor/google/yogi/proprietary/vendor/etc/bluetooth_power_limits_US.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_US.csv \
    vendor/google/yogi/proprietary/vendor/etc/bm_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/bm_config.json \
    vendor/google/yogi/proprietary/vendor/etc/chre/activity.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/activity.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/activity.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/activity.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/aidb_recorder.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/aidb_recorder.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/aidb_recorder.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/aidb_recorder.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/ambient_volume.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ambient_volume.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/ambient_volume.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ambient_volume.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/ar_bridge.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ar_bridge.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/ar_bridge.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ar_bridge.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/blue.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/blue.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/blue.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/blue.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/capo.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/capo.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/capo.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/capo.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/cc.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/cc.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/cc.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/cc.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/columbus.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/columbus.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/columbus.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/columbus.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/columbus_lite.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/columbus_lite.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/columbus_lite.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/columbus_lite.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/dck_gating.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/dck_gating.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/dck_gating.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/dck_gating.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/drop.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/drop.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/drop.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/drop.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/gesture.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/gesture.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/gesture.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/gesture.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/health.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/health.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/health.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/health.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/hh.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/hh.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/hh.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/hh.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/imu_cal.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/imu_cal.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/imu_cal.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/imu_cal.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/instant_sense.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/instant_sense.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/instant_sense.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/instant_sense.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/ip_health.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ip_health.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/ip_health.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ip_health.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/libchre_log_database.bin:$(TARGET_COPY_OUT_VENDOR)/etc/chre/libchre_log_database.bin \
    vendor/google/yogi/proprietary/vendor/etc/chre/location.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/location.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/location.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/location.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/motiondetector.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/motiondetector.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/motiondetector.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/motiondetector.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/nearby.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/nearby.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/nearby.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/nearby.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/sd.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sd.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/sd.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sd.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/sensorcollector.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sensorcollector.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/sensorcollector.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sensorcollector.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/structural_health.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/structural_health.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/structural_health.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/structural_health.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/system_signal_hub.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/system_signal_hub.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/system_signal_hub.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/system_signal_hub.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/time_sync.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/time_sync.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/time_sync.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/time_sync.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/vice.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/vice.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/vice.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/vice.so \
    vendor/google/yogi/proprietary/vendor/etc/chre/wallaby.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/wallaby.napp_header \
    vendor/google/yogi/proprietary/vendor/etc/chre/wallaby.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/wallaby.so \
    vendor/google/yogi/proprietary/vendor/etc/devicestate/device_state_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/devicestate/device_state_configuration.xml \
    vendor/google/yogi/proprietary/vendor/etc/display/hbm_lookup_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/hbm_lookup_tables.xml \
    vendor/google/yogi/proprietary/vendor/etc/display_colordata_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_colordata_cal0.pb \
    vendor/google/yogi/proprietary/vendor/etc/display_colordata_cal1.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_colordata_cal1.pb \
    vendor/google/yogi/proprietary/vendor/etc/display_colordata_google-iyida_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_colordata_google-iyida_cal0.pb \
    vendor/google/yogi/proprietary/vendor/etc/display_colordata_google-iyidb_cal1.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_colordata_google-iyidb_cal1.pb \
    vendor/google/yogi/proprietary/vendor/etc/display_golden_google-iyida_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_golden_google-iyida_cal0.pb \
    vendor/google/yogi/proprietary/vendor/etc/display_golden_google-iyidb_cal1.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_golden_google-iyidb_cal1.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_aical_google-iyida.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_aical_google-iyida.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_aical_google-iyidb.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_aical_google-iyidb.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_cgc_inference_google-iyida.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_cgc_inference_google-iyida.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_cgc_inference_google-iyidb.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_cgc_inference_google-iyidb.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_cgc_pool_google-iyida.bin:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_cgc_pool_google-iyida.bin \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_cgc_pool_google-iyidb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_cgc_pool_google-iyidb.bin \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_colorcal_desc_data_google-iyida.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_colorcal_desc_data_google-iyida.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_colorcal_desc_data_google-iyidb.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_colorcal_desc_data_google-iyidb.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_hbm_regamma_inference_google-iyida.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_hbm_regamma_inference_google-iyida.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_hbm_regamma_inference_google-iyidb.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_hbm_regamma_inference_google-iyidb.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_hbm_regamma_pool_google-iyida.bin:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_hbm_regamma_pool_google-iyida.bin \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_hbm_regamma_pool_google-iyidb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_hbm_regamma_pool_google-iyidb.bin \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_layout_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_layout_configuration.xml \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_nbm_regamma_inference_google-iyida.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_nbm_regamma_inference_google-iyida.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_nbm_regamma_inference_google-iyidb.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_nbm_regamma_inference_google-iyidb.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_nbm_regamma_pool_google-iyida.bin:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_nbm_regamma_pool_google-iyida.bin \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_nbm_regamma_pool_google-iyidb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_nbm_regamma_pool_google-iyidb.bin \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_port_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_port_0.xml \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_port_1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_port_1.xml \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_sharpness_google-iyida_0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_sharpness_google-iyida_0.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_sharpness_google-iyidb_1.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_sharpness_google-iyidb_1.pb \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/display_text_classifier.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_text_classifier.tflite \
    vendor/google/yogi/proprietary/vendor/etc/displayconfig/ltm_td_common.pb:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/ltm_td_common.pb \
    vendor/google/yogi/proprietary/vendor/etc/distonomy_s.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/distonomy_s.tflite \
    vendor/google/yogi/proprietary/vendor/etc/dma_heap.json:$(TARGET_COPY_OUT_VENDOR)/etc/dma_heap.json \
    vendor/google/yogi/proprietary/vendor/etc/earcheek_classifier.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/earcheek_classifier.tflite \
    vendor/google/yogi/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/google/yogi/proprietary/vendor/etc/edgetpu/custom_kernel.pbtxt:$(TARGET_COPY_OUT_VENDOR)/etc/edgetpu/custom_kernel.pbtxt \
    vendor/google/yogi/proprietary/vendor/etc/fstab.gem5:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.gem5 \
    vendor/google/yogi/proprietary/vendor/etc/fstab.malibu:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.malibu \
    vendor/google/yogi/proprietary/vendor/etc/fstab.malibu-fips:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.malibu-fips \
    vendor/google/yogi/proprietary/vendor/etc/fstab.modem:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.modem \
    vendor/google/yogi/proprietary/vendor/etc/fstab.modem_data:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.modem_data \
    vendor/google/yogi/proprietary/vendor/etc/fstab.persist:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.persist \
    vendor/google/yogi/proprietary/vendor/etc/future_vt_prediction_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/future_vt_prediction_model.tflite \
    vendor/google/yogi/proprietary/vendor/etc/gnss/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/MNL_Config.xml \
    vendor/google/yogi/proprietary/vendor/etc/gnss/gnss.cer:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gnss.cer \
    vendor/google/yogi/proprietary/vendor/etc/gnss/gnss_dbg_ctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gnss_dbg_ctrl.cfg \
    vendor/google/yogi/proprietary/vendor/etc/gnss/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.conf \
    vendor/google/yogi/proprietary/vendor/etc/gnss/mnl.prop:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/mnl.prop \
    vendor/google/yogi/proprietary/vendor/etc/gnss/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/mpe.conf \
    vendor/google/yogi/proprietary/vendor/etc/gps_debug.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps_debug.conf \
    vendor/google/yogi/proprietary/vendor/etc/init.common.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.common.cfg \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.audio.service-aidl.aoc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio.service-aidl.aoc.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.authsecret-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.authsecret-service.citadel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.bluetooth-service.bcmbtlinux.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth-service.bcmbtlinux.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.boot-service.default-pixel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.boot-service.default-pixel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.camera.provider@2.7-service-google-apex.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.7-service-google-apex.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.contexthub-service.generic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.contexthub-service.generic.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.dumpstate.3-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.dumpstate.3-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.edgetpu.logging@service-edgetpu-logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.edgetpu.logging@service-edgetpu-logging.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.gxp.logging@service-gxp-logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gxp.logging@service-gxp-logging.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.health-service.malibu.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health-service.malibu.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.input.processor-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.input.processor-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.neuralnetworks@service-darwinn-aidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@service-darwinn-aidl.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.oemlock-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.oemlock-service.citadel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.power-service.pixel-libperfmgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power-service.pixel-libperfmgr.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.power.stats-service.pixel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power.stats-service.pixel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.samsung.uwb-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.samsung.uwb-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.security.keymint-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.citadel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.thermal-service.pixel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal-service.pixel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.usb-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.usb.gadget-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb.gadget-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.vibrator-service.cs40l26-rust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.vibrator-service.cs40l26-rust.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/android.hardware.weaver-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.weaver-service.citadel.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/aocd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aocd.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/aocxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aocxd.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/citadeld.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/citadeld.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/com.google.edgetpu.tachyon-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.google.edgetpu.tachyon-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/com.google.input.gia.giacore.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.google.input.gia.giacore.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/devcoredump_action.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/devcoredump_action.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/drm_hwc3.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/drm_hwc3.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/dump_power.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dump_power.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/fingerprint-goodix.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fingerprint-goodix.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/gnss_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gnss_daemon.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/gnss_dbg_ctrl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gnss_dbg_ctrl.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/gnss_fw_log.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gnss_fw_log.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/gnss_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gnss_manager.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/gnss_pal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gnss_pal.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/google.hardware.image-V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/google.hardware.image-V1-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/google.hardware.media.c2@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/google.hardware.media.c2@3.0-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/gpuflag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gpuflag.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/hw/init.dpa.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.dpa.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/hw/init.malibu.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.malibu.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/hw/init.malibu.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.malibu.usb.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/hw/init.modem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.modem.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/hw/init.modem_data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.modem_data.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/hw/init.yogi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.yogi.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/imsmediahaldaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsmediahaldaemon.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.aoc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.aoc.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.camera.set-interrupts-ownership.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.camera.set-interrupts-ownership.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.gia.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gia.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.gsa.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gsa.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.interrupts.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.interrupts.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.mailbox.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.mailbox.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.modem_logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.modem_logging.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.module.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.module.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.pixel-mm-gs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.pixel-mm-gs.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.pixel-perf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.pixel-perf.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.pixel_irq_load_balancer.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.pixel_irq_load_balancer.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.power-gs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.power-gs.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.shared_modem_platform_a.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.shared_modem_platform_a.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.sscoredump.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sscoredump.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.storage.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.touch.gti0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.touch.gti0.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.touch.gti1.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.touch.gti1.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.usboffmode.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.usboffmode.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.usf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.usf.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init.watermark-scale-factor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.watermark-scale-factor.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init_epic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_epic.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/init_rdbl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_rdbl.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/libg3a_gabc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/libg3a_gabc.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/libg3a_gaf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/libg3a_gaf.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/libg3a_ghawb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/libg3a_ghawb.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/md_rfs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/md_rfs.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/mdl_coll.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mdl_coll.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/memtrack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/mtk_lbs_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_lbs_service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/mtk_remotefsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_remotefsd.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/mtk_thinmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_thinmd.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/nfc2-service-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nfc2-service-default.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pcie_power.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pcie_power.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-bgtasks-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-bgtasks-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-dmabuf-deferred-free-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-dmabuf-deferred-free-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-experiments-recovery.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-experiments-recovery.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-min-gcma-dmabuf-kb-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-min-gcma-dmabuf-kb-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-pbmprofile-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-pbmprofile-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-sched-proxy-exec-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-sched-proxy-exec-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-thermal-symlinks.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-thermal-symlinks.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-zram-comp-algorithm-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-zram-comp-algorithm-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel-zram-swap-size-experiment.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel-zram-swap-size-experiment.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixel.gralloc.allocator-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixel.gralloc.allocator-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/pixelstats-vendor.malibu.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixelstats-vendor.malibu.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/sap_log.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/sap_log.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/storage.init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/storage.init.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/storage.intelligence.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/storage.intelligence.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/trusty_metricsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusty_metricsd.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/twoshay.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/twoshay.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/uwb-calib.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/uwb-calib.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.dolby.media.c2-default-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2-default-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.ambience_hub-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.ambience_hub-default.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.battery_mitigation-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.battery_mitigation-default.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.edgetpu_vendor_service@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.edgetpu_vendor_service@1.0-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.google_battery-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.google_battery-default.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.lights-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.lights-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.plat_security-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.plat_security-service.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.wireless_charger-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.wireless_charger-default.rc \
    vendor/google/yogi/proprietary/vendor/etc/init/vendor.google.wireless_charger.service-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.wireless_charger.service-default.rc \
    vendor/google/yogi/proprietary/vendor/etc/input-port-associations.xml:$(TARGET_COPY_OUT_VENDOR)/etc/input-port-associations.xml \
    vendor/google/yogi/proprietary/vendor/etc/input_classifier_model.pb:$(TARGET_COPY_OUT_VENDOR)/etc/input_classifier_model.pb \
    vendor/google/yogi/proprietary/vendor/etc/input_classifier_model_ext.pb:$(TARGET_COPY_OUT_VENDOR)/etc/input_classifier_model_ext.pb \
    vendor/google/yogi/proprietary/vendor/etc/le_audio_codec_capabilities.xml:$(TARGET_COPY_OUT_VENDOR)/etc/le_audio_codec_capabilities.xml \
    vendor/google/yogi/proprietary/vendor/etc/libg3a_standalone_gabc_rc:$(TARGET_COPY_OUT_VENDOR)/etc/libg3a_standalone_gabc_rc \
    vendor/google/yogi/proprietary/vendor/etc/libg3a_standalone_gaf_rc:$(TARGET_COPY_OUT_VENDOR)/etc/libg3a_standalone_gaf_rc \
    vendor/google/yogi/proprietary/vendor/etc/libg3a_standalone_ghawb_rc:$(TARGET_COPY_OUT_VENDOR)/etc/libg3a_standalone_ghawb_rc \
    vendor/google/yogi/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/google/yogi/proprietary/vendor/etc/libnfc-hal-st_p1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st_p1.conf \
    vendor/google/yogi/proprietary/vendor/etc/libse-gto-hal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libse-gto-hal.conf \
    vendor/google/yogi/proprietary/vendor/etc/mdl_coll_default.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mdl_coll_default.cfg \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_COMBO_NWOTA_APAC_COMMON_SBPID_158_426_02.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_COMBO_NWOTA_APAC_COMMON_SBPID_158_426_02.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_COMBO_NWOTA_APAC_COMMON_SBPID_221__.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_COMBO_NWOTA_APAC_COMMON_SBPID_221__.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_COMBO_NWOTA_ATT_SBPID_267__.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_COMBO_NWOTA_ATT_SBPID_267__.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_COMBO_NWOTA_EU_COMMON_SBPID_158_420_04.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_COMBO_NWOTA_EU_COMMON_SBPID_158_420_04.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_COMBO_NWOTA_VZW_SBPID_446__.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_COMBO_NWOTA_VZW_SBPID_446__.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_001_01.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_001_01.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_302.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_302.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_310.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_310.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_311.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_311.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_312.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_312.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_313.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_313.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_314.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_314.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_315.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_315.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_316.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_316.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_440.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_440.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_GENERAL_441.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_GENERAL_441.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_10001.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_10001.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_10002.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_10002.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_1003.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_1003.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_102.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_102.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_103.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_103.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_104.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_104.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_106.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_106.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_107.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_107.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_108.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_108.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_109.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_109.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_11.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_11.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_110.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_110.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_111.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_111.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_112.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_112.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_114.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_114.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_115.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_115.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_116.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_116.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_12.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_12.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_121.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_121.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_122.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_122.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_126.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_126.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_129.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_129.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_130.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_130.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_132.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_132.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_137.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_137.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_139.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_139.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_145.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_145.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_147.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_147.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_15.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_15.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_151.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_151.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_152.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_152.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_153.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_153.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_154.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_154.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_156.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_156.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_157.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_157.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_158.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_158.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_159.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_159.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_16.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_16.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_162.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_162.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_17.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_17.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_175.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_175.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_176.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_176.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_18.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_18.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_188.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_188.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_19.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_19.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_196.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_196.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_20.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_20.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_201.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_201.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_202.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_202.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_203.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_203.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_204.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_204.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_21.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_21.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_210.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_210.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_218.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_218.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_221.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_221.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_227.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_227.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_236.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_236.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_237.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_237.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_238.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_238.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_267.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_267.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_283.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_283.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_287.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_287.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_293.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_293.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_3.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_3.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_303.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_303.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_327.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_327.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_333.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_333.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_336.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_336.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_363.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_363.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_422.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_422.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_446.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_446.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_452.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_452.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_5.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_5.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_50.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_50.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_6.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_6.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_7.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_7.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_NWOTA_SBPID_8.mcfnwota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_NWOTA_SBPID_8.mcfnwota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_ATT_MX.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_ATT_MX.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_GENERAL.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_GENERAL.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_GENERAL_001_01.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_GENERAL_001_01.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_GENERAL_334.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_GENERAL_334.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_GENERAL_466.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_GENERAL_466.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_GENERAL_999.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_GENERAL_999.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_O2_DE.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_O2_DE.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_O2_GB.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_O2_GB.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_ORANGE_FR.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_ORANGE_FR.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_10001.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_10001.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_10002.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_10002.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_10003.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_10003.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_103.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_103.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_104.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_104.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_107.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_107.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_11.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_11.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_111.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_111.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_12.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_12.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_121.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_121.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_128.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_128.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_129.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_129.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_134.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_134.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_137.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_137.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_139.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_139.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_145.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_145.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_147.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_147.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_15.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_15.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_151.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_151.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_154.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_154.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_157.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_157.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_16.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_16.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_162.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_162.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_165.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_165.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_17.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_17.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_18.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_18.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_182.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_182.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_189.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_189.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_19.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_19.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_195.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_195.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_20.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_20.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_204.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_204.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_206.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_206.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_21.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_21.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_218.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_218.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_231.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_231.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_287.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_287.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_3.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_3.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_327.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_327.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_441.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_441.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_446.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_446.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_447.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_447.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_452.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_452.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_5.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_5.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_50.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_50.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_6.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_6.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_7.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_7.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_SBPID_8.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_SBPID_8.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TDC_DK.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TDC_DK.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELCEL_MX.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELCEL_MX.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELE2_SE.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELE2_SE.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELEKOM_AIRBUS_DE.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELEKOM_AIRBUS_DE.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELEKOM_DE.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELEKOM_DE.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELEKOM_ODIDO_NL.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELEKOM_ODIDO_NL.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELIA_DK.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELIA_DK.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TELIA_NAF_NO.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TELIA_NAF_NO.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_THREE_AT.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_THREE_AT.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_THREE_GB.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_THREE_GB.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_THREE_IE.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_THREE_IE.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_TMO_US_PRIVATE_NETWORK.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_TMO_US_PRIVATE_NETWORK.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_VODAFONE_DE.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_VODAFONE_DE.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OPOTA_VODAFONE_GB.mcfopota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OPOTA_VODAFONE_GB.mcfopota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OTA.mcfota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OTA.mcfota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OTA_Fold.mcfota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OTA_Fold.mcfota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OTA_MMW.mcfota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OTA_MMW.mcfota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/MTK_OTA_SUB6.mcfota:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/MTK_OTA_SUB6.mcfota \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/carrier_config_a900a-MP_260716-260727-M-15947729:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/carrier_config_a900a-MP_260716-260727-M-15947729 \
    vendor/google/yogi/proprietary/vendor/etc/mdota/custom/mcf_file_sec.bin:$(TARGET_COPY_OUT_VENDOR)/etc/mdota/custom/mcf_file_sec.bin \
    vendor/google/yogi/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/google/yogi/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/google/yogi/proprietary/vendor/etc/media_codecs_dolby_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_c2.xml \
    vendor/google/yogi/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/google/yogi/proprietary/vendor/etc/media_codecs_performance_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_c2.xml \
    vendor/google/yogi/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/google/yogi/proprietary/vendor/etc/memory-limiter-config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/memory-limiter-config.xml \
    vendor/google/yogi/proprietary/vendor/etc/modem_stat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/modem_stat.conf \
    vendor/google/yogi/proprietary/vendor/etc/panel_config_google-iyida_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/panel_config_google-iyida_cal0.pb \
    vendor/google/yogi/proprietary/vendor/etc/panel_config_google-iyidb_cal1.pb:$(TARGET_COPY_OUT_VENDOR)/etc/panel_config_google-iyidb_cal1.pb \
    vendor/google/yogi/proprietary/vendor/etc/panel_ctrl_google-iyida_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/panel_ctrl_google-iyida_cal0.pb \
    vendor/google/yogi/proprietary/vendor/etc/panel_ctrl_google-iyidb_cal1.pb:$(TARGET_COPY_OUT_VENDOR)/etc/panel_ctrl_google-iyidb_cal1.pb \
    vendor/google/yogi/proprietary/vendor/etc/permissions/android.hardware.npu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.npu.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/android.hardware.strongbox_keystore_v4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.strongbox_keystore_v4.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/android.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.gsm.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/android.hardware.telephony.ims.prebuilt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.ims.prebuilt.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/android.hardware.telephony.satellite.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.satellite.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/android.hardware.uwb.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.uwb.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/com.google.android.camera.experimental2026.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.google.android.camera.experimental2026.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/com.google.android.hardwareinfo.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.google.android.hardwareinfo.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/com.google.pixel.camera.concurrent_foldable_dual_front.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.google.pixel.camera.concurrent_foldable_dual_front.xml \
    vendor/google/yogi/proprietary/vendor/etc/permissions/vendor.android.hardware.camera.preview-dis.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.android.hardware.camera.preview-dis.xml \
    vendor/google/yogi/proprietary/vendor/etc/pixelstats_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/pixelstats_config.json \
    vendor/google/yogi/proprietary/vendor/etc/powerhint.json:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.json \
    vendor/google/yogi/proprietary/vendor/etc/powervr.ini:$(TARGET_COPY_OUT_VENDOR)/etc/powervr.ini \
    vendor/google/yogi/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/google/yogi/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_common.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_common.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_dvt.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_dvt.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_evt_1_0.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_evt_1_0.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_evt_1_1.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_evt_1_1.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_proto_1_0.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_proto_1_0.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_proto_1_0_led.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_proto_1_0_led.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_proto_1_1.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_proto_1_1.reg \
    vendor/google/yogi/proprietary/vendor/etc/sensors/registry/yogi_proto_1_1_old_flam.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/yogi_proto_1_1_old_flam.reg \
    vendor/google/yogi/proprietary/vendor/etc/sysconfig/vendor-apex-allowlist-audio-resource.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sysconfig/vendor-apex-allowlist-audio-resource.xml \
    vendor/google/yogi/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/google/yogi/proprietary/vendor/etc/telephony/satellite_access_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/telephony/satellite_access_config.json \
    vendor/google/yogi/proprietary/vendor/etc/telephony/sats2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/telephony/sats2.dat \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_aa_throttling.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_aa_throttling.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_bg_tasks_throttling.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_bg_tasks_throttling.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_charge.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_charge.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_charge_no_quiet.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_charge_no_quiet.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_earlywarnings.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_earlywarnings.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_forecast.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_forecast.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_no_quiet.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_no_quiet.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_info_config_vt.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_vt.json \
    vendor/google/yogi/proprietary/vendor/etc/thermal_powerbudgets.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_powerbudgets.json \
    vendor/google/yogi/proprietary/vendor/etc/thinmd_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/thinmd_cfg.ini \
    vendor/google/yogi/proprietary/vendor/etc/touchflow_inner.pb:$(TARGET_COPY_OUT_VENDOR)/etc/touchflow_inner.pb \
    vendor/google/yogi/proprietary/vendor/etc/touchflow_outer.pb:$(TARGET_COPY_OUT_VENDOR)/etc/touchflow_outer.pb \
    vendor/google/yogi/proprietary/vendor/etc/tracing_descriptors.gz:$(TARGET_COPY_OUT_VENDOR)/etc/tracing_descriptors.gz \
    vendor/google/yogi/proprietary/vendor/etc/twoshay_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/twoshay_config.json \
    vendor/google/yogi/proprietary/vendor/etc/twoshay_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/twoshay_config.pb \
    vendor/google/yogi/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_cal_region-ce.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_cal_region-ce.json \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_cal_region-default.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_cal_region-default.json \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_cal_region-fcc.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_cal_region-fcc.json \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_cal_region-jp.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_cal_region-jp.json \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_cal_region-tw.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_cal_region-tw.json \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_hal_conf.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_hal_conf.json \
    vendor/google/yogi/proprietary/vendor/etc/uwb/samsung_uwb_region.json:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/samsung_uwb_region.json \
    vendor/google/yogi/proprietary/vendor/etc/vt_bottom_speaker_estimation_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/vt_bottom_speaker_estimation_model.tflite \
    vendor/google/yogi/proprietary/vendor/etc/vt_estimation_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/vt_estimation_model.tflite \
    vendor/google/yogi/proprietary/vendor/etc/vt_estimation_model_no_quiet.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/vt_estimation_model_no_quiet.tflite \
    vendor/google/yogi/proprietary/vendor/etc/vt_estimation_odpm_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/vt_estimation_odpm_model.tflite \
    vendor/google/yogi/proprietary/vendor/etc/vt_speaker_estimation_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/vt_speaker_estimation_model.tflite \
    vendor/google/yogi/proprietary/vendor/etc/vt_top_speaker_estimation_model.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/vt_top_speaker_estimation_model.tflite \
    vendor/google/yogi/proprietary/vendor/etc/water-clf-inner.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/water-clf-inner.tflite \
    vendor/google/yogi/proprietary/vendor/etc/water-clf-outer.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/water-clf-outer.tflite \
    vendor/google/yogi/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/google/yogi/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/google/yogi/proprietary/vendor/firmware/3626.app:$(TARGET_COPY_OUT_VENDOR)/firmware/3626.app \
    vendor/google/yogi/proprietary/vendor/firmware/CPS4041_A0_0A.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CPS4041_A0_0A.bin \
    vendor/google/yogi/proprietary/vendor/firmware/CPS4041_BL.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CPS4041_BL.bin \
    vendor/google/yogi/proprietary/vendor/firmware/CPS8200.signed.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CPS8200.signed.bin \
    vendor/google/yogi/proprietary/vendor/firmware/aoc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aoc.bin \
    vendor/google/yogi/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/google/yogi/proprietary/vendor/firmware/batt_fw_adi_79_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/batt_fw_adi_79_3.bin \
    vendor/google/yogi/proprietary/vendor/firmware/bcmdhd.cal_4390_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd.cal_4390_b1 \
    vendor/google/yogi/proprietary/vendor/firmware/bcmdhd.cal_USI_G7BB_7311_V11:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd.cal_USI_G7BB_7311_V11 \
    vendor/google/yogi/proprietary/vendor/firmware/bcmdhd_clm.blob_4390_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_clm.blob_4390_b1 \
    vendor/google/yogi/proprietary/vendor/firmware/bcmdhd_txcap.blob_4390_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_txcap.blob_4390_b1 \
    vendor/google/yogi/proprietary/vendor/firmware/brcm/BCM.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/brcm/BCM.hcd \
    vendor/google/yogi/proprietary/vendor/firmware/brcm/BTFW_B.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/brcm/BTFW_B.hcd \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.bin \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26-calib.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.wmfw \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26-dbc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-dbc.bin \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26-dvl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-dvl.bin \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26-svc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc.bin \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.bin \
    vendor/google/yogi/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/google/yogi/proprietary/vendor/firmware/epic/gb00.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/epic/gb00.ec.bin \
    vendor/google/yogi/proprietary/vendor/firmware/epic/pi01.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/epic/pi01.ec.bin \
    vendor/google/yogi/proprietary/vendor/firmware/filter_ie:$(TARGET_COPY_OUT_VENDOR)/firmware/filter_ie \
    vendor/google/yogi/proprietary/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin \
    vendor/google/yogi/proprietary/vendor/firmware/fw_bcmdhd.bin_4390_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin_4390_b1 \
    vendor/google/yogi/proprietary/vendor/firmware/fw_bcmdhd.map:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.map \
    vendor/google/yogi/proprietary/vendor/firmware/fw_bcmdhd.map_4390_b1:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.map_4390_b1 \
    vendor/google/yogi/proprietary/vendor/firmware/google/edgetpu-santafe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/google/edgetpu-santafe.fw \
    vendor/google/yogi/proprietary/vendor/firmware/google/gxp-metis.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/google/gxp-metis.fw \
    vendor/google/yogi/proprietary/vendor/firmware/gxp_metis_fw_core0:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_metis_fw_core0 \
    vendor/google/yogi/proprietary/vendor/firmware/gxp_metis_fw_core1:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_metis_fw_core1 \
    vendor/google/yogi/proprietary/vendor/firmware/malibu_pcie_phy_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/malibu_pcie_phy_fw.bin \
    vendor/google/yogi/proprietary/vendor/firmware/ncp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ncp.bin \
    vendor/google/yogi/proprietary/vendor/firmware/nep.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nep.bin \
    vendor/google/yogi/proprietary/vendor/firmware/rdbl.img:$(TARGET_COPY_OUT_VENDOR)/firmware/rdbl.img \
    vendor/google/yogi/proprietary/vendor/firmware/rgx.fw.70.3.2448.1042:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.fw.70.3.2448.1042 \
    vendor/google/yogi/proprietary/vendor/firmware/rgx.fw.signed.70.3.2448.1042:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.fw.signed.70.3.2448.1042 \
    vendor/google/yogi/proprietary/vendor/firmware/rgx.sh.70.3.2448.1042:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.sh.70.3.2448.1042 \
    vendor/google/yogi/proprietary/vendor/firmware/s6e3ft0_img.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/s6e3ft0_img.bin \
    vendor/google/yogi/proprietary/vendor/firmware/s6e3ft0_selftest_limit.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/s6e3ft0_selftest_limit.csv \
    vendor/google/yogi/proprietary/vendor/firmware/sarconfig.info:$(TARGET_COPY_OUT_VENDOR)/firmware/sarconfig.info \
    vendor/google/yogi/proprietary/vendor/firmware/seurat.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/seurat.bin \
    vendor/google/yogi/proprietary/vendor/firmware/st54l_conf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st54l_conf.bin \
    vendor/google/yogi/proprietary/vendor/firmware/st54l_conf_p1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st54l_conf_p1.bin \
    vendor/google/yogi/proprietary/vendor/firmware/st54l_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st54l_fw.bin \
    vendor/google/yogi/proprietary/vendor/firmware/st_fts.ubin:$(TARGET_COPY_OUT_VENDOR)/firmware/st_fts.ubin \
    vendor/google/yogi/proprietary/vendor/firmware/stm_fts_production_limits.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/stm_fts_production_limits.csv \
    vendor/google/yogi/proprietary/vendor/firmware/ti_sp_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ti_sp_tuning.bin \
    vendor/google/yogi/proprietary/vendor/firmware/tismartpa_driver_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tismartpa_driver_tuning.bin \
    vendor/google/yogi/proprietary/vendor/firmware/tx_mcu.signed.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tx_mcu.signed.bin \
    vendor/google/yogi/proprietary/vendor/firmware/u100FwUpdate.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/u100FwUpdate.bin \
    vendor/google/yogi/proprietary/vendor/firmware/u100FwUpdate_test.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/u100FwUpdate_test.bin \
    vendor/google/yogi/proprietary/vendor/firmware/usb_phy_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/usb_phy_fw.bin \
    vendor/google/yogi/proprietary/vendor/firmware/usb_phy_fw_2.27.0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/usb_phy_fw_2.27.0.bin \
    vendor/google/yogi/proprietary/vendor/framework/oat/arm64/com.google.android.camera.experimental2026.odex:$(TARGET_COPY_OUT_VENDOR)/framework/oat/arm64/com.google.android.camera.experimental2026.odex \
    vendor/google/yogi/proprietary/vendor/framework/oat/arm64/com.google.android.camera.experimental2026.vdex:$(TARGET_COPY_OUT_VENDOR)/framework/oat/arm64/com.google.android.camera.experimental2026.vdex

PRODUCT_PACKAGES += \
    aconfig_gpu_flags_c_lib \
    aconfig_gpu_img_flags_c_lib \
    aconfig_gsc_flags_c_lib \
    android.hardware.authsecret-impl.nos \
    android.hardware.gnss-V7-ndk \
    android.hardware.light-V3-ndk \
    android.hardware.nfc-V2-ndk \
    android.hardware.npu-V1-ndk \
    android.hardware.oemlock-impl.nos \
    android.hardware.power.stats-impl.malibu \
    android.hardware.power.stats-impl.pixel \
    android.hardware.power@1.0 \
    android.hardware.power@1.1 \
    android.hardware.power@1.2 \
    android.hardware.radio-V5-ndk \
    android.hardware.radio.config-V5-ndk \
    android.hardware.radio.data-V5-ndk \
    android.hardware.radio.ims-V4-ndk \
    android.hardware.radio.ims.media-V2-ndk \
    android.hardware.radio.messaging-V5-ndk \
    android.hardware.radio.modem-V5-ndk \
    android.hardware.radio.network-V5-ndk \
    android.hardware.radio.sim-V5-ndk \
    android.hardware.radio.voice-V5-ndk \
    android.hardware.security.keymint-V4-ndk \
    android.hardware.security.keymint-impl.nos \
    android.hardware.weaver-bridge.nos \
    android.hardware.weaver-impl.nos \
    android.hardware.weaver2-impl.nos \
    android.system.keystore2-V6-ndk \
    aoc_aconfig_flags_c_lib \
    aocx-V3-ndk \
    biometricsuez \
    com.google.edgetpu.tachyon-ndk \
    com.google.edgetpu_app_service-V10-ndk_vendor \
    com.google.edgetpu_vendor_service-V2-ndk_vendor \
    com.google.hardware.biometrics.parcelable.fingerprint.PressToAuthParcelable-V1-ndk \
    com.google.hardware.biometrics.sidefps.fingerprint-ext-V1-ndk \
    com.google.hardware.pixel.display-V22-ndk \
    com.google.input-V8-ndk \
    com.google.pixel.modem_logging.log_files-ndk \
    libEGL_powervr \
    libGLESv1_CM_powervr \
    libGLESv2_powervr \
    fake_gxp_telemetry_reader \
    fake_libtachyon_core \
    goodix_sfps_suez \
    goodixbinderservice-aidl-V1-ndk \
    goodixfingerprint \
    google.hardware.image-V1-ndk \
    gxp_metrics_logger \
    gxp_telemetry_reader \
    hardware.google.ril_ext-V2-ndk \
    android.hardware.gnss-impl-mediatek \
    gps.default \
    gsc_image_tools \
    libDReap \
    libgnssdbgctrl \
    libgnssmonitor \
    libgnssspectrum \
    libgnsssupl \
    libgsc_updater \
    mapper.pixel \
    mtk_lbs_service-impl \
    vulkan.powervr \
    libIMGegl \
    libMAM_Google_Pixel_Android \
    libNX_Google_Pixel_Android \
    libOpenCL-pixel \
    libPVROCL \
    libPVRScopeServices \
    libPixelGrallocProperties \
    lib_aion_buffer \
    lib_jpg_encoder \
    lib_modemcommlayer \
    lib_mtklogformat \
    lib_reader \
    lib_recycle \
    lib_snappy \
    lib_toolcommlayer \
    lib_vendor_gsc_atoms \
    libalertv3 \
    libaoc \
    libc2filterplugin \
    libcarrierconfig \
    libcodec2_soft_ddpdec \
    libcodec2_store_dolby \
    libcustom_nvram \
    libcustomer_gralloc_ddk_api \
    libdarwinn_hal \
    libdeeptouch \
    libdisplay_tflite \
    libdisplayambience \
    libdisplaycolor \
    libdisplaypanel \
    libdump \
    libedgetpu_client.google \
    libedgetpu_litert \
    libedgetpu_tachyon.google \
    libedgetpu_tflite_compiler \
    libedgetpu_util \
    libepic_version_utils \
    libfile_op \
    libfvsam_prm_parser \
    libgc2_av1_dec \
    libgc2_av1_enc \
    libgc2_avc_dec \
    libgc2_avc_enc \
    libgc2_base \
    libgc2_dec \
    libgc2_enc \
    libgc2_filter_common \
    libgc2_hal_flags \
    libgc2_hevc_dec \
    libgc2_hevc_enc \
    libgc2_log \
    libgc2_store \
    libgc2_utils \
    libgc2_vdi_vpu \
    libgc2_vp9_dec \
    libgf_ca \
    libgf_hal \
    libgooglerilaudio \
    libgooglerilmemmonitor \
    libgpudataproducer \
    libgpuflag_aconfig_rust \
    libgxp \
    libhwc_flags \
    libhwc_xrr_flags \
    libhwjpeg \
    libimgcodec_comp \
    libimgcodec_jdi_jpu \
    libimgcodec_log \
    libimgcodec_store \
    libimsmediahalproxy_mtk \
    libion_google \
    libkeymint_support_V4 \
    libmahalcontroller \
    libmdspeech \
    libmemtrack-pixel \
    libmetrics_logger \
    libmipc_vendor \
    libmnl \
    libmtkconfig \
    libmtkconfigutils \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkproperty_vendor \
    libmtkrillog_vendor \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libnos_citadeld_proxy \
    libnvram \
    libnvram_platform \
    libnvram_sec \
    liboemcrypto \
    libperfetto_c \
    libperfmgr \
    libphone_booth_model_darwinn \
    libpixelatoms_defs \
    libpixelhealth \
    libpixelstats \
    libpixelstatsflags \
    libratconfig \
    libril_hallog \
    librilfusion \
    librtxproto_aidl-default \
    libspeechenhancer \
    libsrv_um \
    libstreset26 \
    libsysutils \
    libtachyon_core \
    libtachyon_dsp_core \
    libthermal_tflite_wrapper \
    libtouchflow \
    libtrm_vendor \
    libufwriter \
    libusc \
    libusf \
    libutils-default \
    libutilscallstack \
    libvadprocessor \
    libwlcproto_aidl-default \
    libwpfa \
    nfc_nci.st21nfc.base \
    pixel_stateresidency_provider_aidl_interface-ndk \
    pixelatoms-cpp \
    pixelstats_flags_c_lib \
    sensors.usf.v2 \
    libpixelhapticgeneratoraidl \
    thermal-budget-interface-ndk \
    usf_v2_api \
    usf_v2_spectral_api \
    vendor-pixelatoms-cpp \
    vendor.google.ambience_hub-V1-ndk \
    vendor.google.ambience_hub.signals-V1-ndk \
    vendor.google.ambience_hub.signals-V3-ndk \
    vendor.google.battery_mitigation-V1-ndk \
    vendor.google.battery_mitigation.service_static \
    vendor.google.bluetooth_ext-V4-ndk \
    vendor.google.gnss.gnss_manager.controller-V2-ndk \
    vendor.google.gnss.gnss_manager.logger-V1-ndk \
    vendor.google.google_battery-V5-ndk \
    vendor.google.plat_security-V1-ndk \
    vendor.google.whitechapel.audio.audioext@4.0_vendor \
    vendor.google.whitechapel.audio.extension-V8-ndk_vendor \
    vendor.google.whitechapel.audio.hal.utils.adaptedinfo.repeated_thread \
    vendor.google.whitechapel.audio.hal.utils.adaptedinfo \
    vendor.google.whitechapel.audio.hal.utils.aoc \
    vendor.google.whitechapel.audio.hal.utils.bluenote \
    vendor.google.whitechapel.audio.hal.utils.pipe \
    vendor.google.whitechapel.audio.hal.utils \
    vendor.google.whitechapel.audio_flags \
    vendor.google.wireless_charger-V8-ndk \
    vendor.google.wireless_charger.service-V2-ndk \
    vendor.mediatek.hardware.lbs-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.assist-V4-ndk \
    vendor.mediatek.hardware.mtkradioex.atci-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.cap-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.data-V3-ndk \
    vendor.mediatek.hardware.mtkradioex.dch-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.em-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.ims-V3-ndk \
    vendor.mediatek.hardware.mtkradioex.messaging-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.modem-V5-ndk \
    vendor.mediatek.hardware.mtkradioex.mwi-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.network-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.ntn-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.rcs-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.rsu-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.se-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.sim-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.sim-V2-ndk \
    vendor.mediatek.hardware.mtkradioex.smartratswitch-V1-ndk \
    vendor.mediatek.hardware.mtkradioex.voice-V1-ndk \
    vendor.mediatek.hardware.netdagent-V1-ndk \
    vendor_chre_atoms_log \
    vendor_chre_metrics-cpp \
    com.google.android.hardware.biometrics.face \
    com.google.android.widevine-15027108-cp2a \
    com.google.pixel.audio.resource \
    com.google.pixel.camera.hal \
    com.google.pixel.euicc.update \
    com.google.pixel.wifi.ext \
    com.google.yogi.hardware.threadnetwork \
    HardwareInfo \
    com.google.android.camera.experimental2026 \
    android.hardware.audio.service-aidl.aoc.xml \
    android.hardware.authsecret-service.citadel.xml \
    android.hardware.bluetooth.socket-service.pixel.xml \
    android.hardware.contexthub-service.generic.xml \
    android.hardware.dumpstate.3-service.xml \
    android.hardware.health-service.malibu.xml \
    android.hardware.neuralnetworks@service-darwinn-aidl.xml \
    android.hardware.oemlock-service.citadel.xml \
    android.hardware.power-service.pixel.xml \
    android.hardware.power.stats-service.pixel.xml \
    android.hardware.samsung.uwb-service.xml \
    android.hardware.security.keymint-service-v4.citadel.xml \
    android.hardware.security.sharesecret-service.citadel.xml \
    android.hardware.thermal-service.pixel.xml \
    android.hardware.usb-service.xml \
    android.hardware.usb.gadget-service.xml \
    android.hardware.vibrator-service.cs40l26-rust.xml \
    android.hardware.weaver-service.citadel.xml \
    com.google.edgetpu.tachyon-service.xml \
    drm_hwc3.xml \
    fingerprint-goodix.xml \
    gnss-default.xml \
    gnss-manager.xml \
    manifest_allocator_aidl.xml \
    manifest_aocx.xml \
    manifest_image_aidl.xml \
    manifest_input.processor-service.xml \
    manifest_mapper_framework.xml \
    manifest_media_c2_cnm.xml \
    memtrack.xml \
    modem_logging.xml \
    mtk_lbs_service.xml \
    nfc2-service-default.xml \
    pixel-display-default.xml \
    pixel-display-secondary.xml \
    shared_modem_platform.xml \
    vendor.dolby.media.c2-default-service.xml \
    vendor.google.ambience_hub-default.xml \
    vendor.google.battery_mitigation-default.xml \
    vendor.google.edgetpu_vendor_service@1.0-service.xml \
    vendor.google.google_battery-default.xml \
    vendor.google.lights-service.xml \
    vendor.google.plat_security-service.xml \
    vendor.google.wireless_charger-default.xml \
    vendor.google.wireless_charger.service-default.xml \
    aical_plugin \
    aocd \
    aocxd \
    devcoredump_action \
    dhd \
    dump_aoc \
    dump_bootlogs_bldr \
    dump_devfreq \
    dump_dwc3 \
    dump_firmware \
    dump_gsa \
    dump_gsc \
    dump_interrupts_traces \
    dump_iommu \
    dump_mailbox \
    dump_modem_log \
    dump_modem_syslog \
    dump_pcie \
    dump_perf \
    dump_pixel_display \
    dump_pixel_metrics \
    dump_pixel_second_display \
    dump_power \
    dump_sensors \
    dump_soc \
    dump_storage \
    dump_telemetry \
    dump_thermal \
    dump_tpu \
    dump_trusty \
    dump_uwb \
    fwtp_tool \
    gia \
    gpuflag \
    android.hardware.audio.service-aidl.aoc \
    android.hardware.authsecret-service.citadel \
    android.hardware.biometrics.fingerprint-service.goodix \
    android.hardware.bluetooth-service.bcmbtlinux \
    android.hardware.boot-service.default-pixel \
    android.hardware.composer.drm-hwc3-service \
    android.hardware.contexthub-service.generic \
    android.hardware.dumpstate.3-service \
    android.hardware.edgetpu.logging@service-edgetpu-logging \
    android.hardware.gnss-service.mediatek \
    android.hardware.gxp.logging@service-gxp-logging \
    android.hardware.health-service.malibu \
    android.hardware.input.processor-service \
    android.hardware.memtrack-service.pixel \
    android.hardware.neuralnetworks@service-darwinn-aidl \
    android.hardware.nfc2-service.st \
    android.hardware.oemlock-service.citadel \
    android.hardware.power-service.pixel-libperfmgr \
    android.hardware.power.stats-service.pixel \
    android.hardware.samsung.uwb-service \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.security.keymint-service.citadel \
    android.hardware.thermal-service.pixel \
    android.hardware.usb-service \
    android.hardware.usb.gadget-service \
    android.hardware.vibrator-service.cs40l26-rust \
    android.hardware.weaver-service.citadel \
    battery_mitigation \
    block_queue_depth \
    citadel_updater \
    citadeld \
    com.google.edgetpu.tachyon-service \
    epic_postinstall_runner \
    gnss_daemon \
    gnss_dbg_ctrl \
    gnss_fw_log \
    gnss_manager \
    gnss_pal \
    google.hardware.image-V1-service \
    google.hardware.media.c2@3.0-service \
    imsmediahaldaemon \
    init_citadel \
    init_rdbl \
    mtk_lbs_service \
    mtkfusionrild \
    pixel.gralloc.allocator-service \
    usboffmode \
    vendor.dolby.media.c2-default-service \
    vendor.google.ambience_hub-service \
    vendor.google.edgetpu_vendor_service@1.0-service \
    vendor.google.google_battery-service \
    vendor.google.lights-service \
    vendor.google.plat_security-service \
    vendor.google.wireless_charger-default \
    vendor.google.wireless_charger.service-default \
    init.camera.set-interrupts-ownership \
    init_uwb_calib \
    insmod \
    md_rfs \
    mdl_coll \
    modem_logging \
    mtk_remotefsd \
    mtk_thinmd \
    muxreport \
    nvram_daemon \
    pcie_power_control \
    pixel-experiments-recovery \
    pixel_irq_load_balancer \
    pixel_postinstall_vendor \
    pixelstats-vendor \
    sap_log \
    sendhint \
    set_fg_model \
    shamp \
    shared_modem_platform \
    sscoredump \
    storage_init \
    storage_intelligence \
    thermal_symlinks \
    trusty_metricsd \
    twoshay \
    wl
